name: Static Analysis

on: [pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install cppcheck
      run: sudo apt-get install -y cppcheck
    - name: run
      run: |
        cppcheck --enable=all --check-level=exhaustive --error-exitcode=1 \
          --suppress=missingIncludeSystem \
          --template="{file}:{line}: {severity}: {message}" \
          -Iinclude src/
